# Generated by Django 4.2 on 2025-12-23 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.providerservice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
