"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$olo5nkc%+da6zv39jqd6-c1$(q)3p34#+(&wtr0u!raitdkln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'  # or wherever you want



# Application definition

INSTALLED_APPS = [
    

     'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
]

AUTH_USER_MODEL = 'booking.CustomUser'




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# myproject/settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Points to C:\Other_PRojects\myproject\static
STATIC_ROOT = BASE_DIR / 'staticfiles'   # For collectstatic

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



JAZZMIN_SETTINGS = {
     "site_title": "HomeService Admin",
     "site_header": " Welcome HomeService Control Panel",
     "site_brand": "HomeService",
     }
#     "site_logo": "logo.png",  # ✅ No 'images/' if it's directly in static/
#     "site_icon": "favicon.ico",  # ✅ Also should be in static/
#     "welcome_sign": "Welcome to HomeService Admin Panel",
#     "copyright": "HomeService Team",
#     "user_avatar": "profile.image",

#     "topmenu_links": [
#         {"name": "Home", "url": "/", "new_window": False},
#         {"model": "auth.User"},
#         {"app": "yourappname"},  # Replace with your actual app name
#     ],

#     "usermenu_links": [
#         {"name": "Visit Site", "url": "/", "icon": "fas fa-globe", "new_window": True},
#     ],

#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "hide_apps": ["sessions"],
#     "hide_models": ["auth.Group"],

#     "icons": {
#         "auth.User": "fas fa-user",
#         "yourapp.Service": "fas fa-tools",
#         "yourapp.Booking": "fas fa-calendar-check",
#         "yourapp.Category": "fas fa-th-list",
#         "yourapp.Review": "fas fa-star",
#     },

#     "order_with_respect_to": [
#         "auth",
#         "yourapp",
#     ],

#     "custom_links": {
#         "yourapp": [
#             {
#                 "name": "Open Website",
#                 "url": "/",
#                 "icon": "fas fa-external-link-alt",
#                 "permissions": ["auth.view_user"],
#             }
#         ]
#     },

#     "theme": "lux",
#     "dark_mode_theme": "cyborg",
#     "use_google_fonts_cdn": True,
# }

